CREATE TABLE platform (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    version INTEGER DEFAULT 0 NOT NULL,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE game (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    version INTEGER DEFAULT 0 NOT NULL,
    platform_ref INTEGER NOT NULL,
    name VARCHAR(500) NOT NULL,
    external_id BIGINT,
    overview_text VARCHAR(10000),
    image_box_art_path VARCHAR(10000),
    image_screen_shot_path VARCHAR(10000),
    image_art_path VARCHAR(10000),
    date_added TIMESTAMP,
    date_last_played TIMESTAMP,
    play_count INTEGER,
    rating INTEGER,
    PRIMARY KEY(id),
    FOREIGN KEY (platform_ref) REFERENCES platform(id)
);

CREATE TABLE game_path (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    version INTEGER DEFAULT 0 NOT NULL,
    game_ref INTEGER NOT NULL,
    file_name VARCHAR(20000) NOT NULL,
    game_path VARCHAR(20000) NOT NULL,    
    PRIMARY KEY(id),
    FOREIGN KEY (game_ref) REFERENCES game(id)
);
