CREATE TABLE platform (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    version INTEGER DEFAULT 0 NOT NULL,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE game (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    version INTEGER DEFAULT 0 NOT NULL,
    platform_ref INTEGER NOT NULL,
    name VARCHAR(200) NOT NULL,
    game_path VARCHAR(200) NOT NULL,
    external_id BIGINT,
    overview_text VARCHAR(200),
    image_box_art_path VARCHAR(200),
    image_screen_shot_path VARCHAR(200),
    image_art_path VARCHAR(200),
    PRIMARY KEY(id),
    FOREIGN KEY (platform_ref) REFERENCES platform(id)
);