DROP TABLE emu_details;

CREATE TABLE emu_details (
        id INTEGER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
        version INTEGER DEFAULT 0 NOT NULL,
        emu_name VARCHAR(26)
);

INSERT INTO emu_details (emu_name) VALUES ('TEST');